package Model;
// Generated 24 Feb 2016 10:33:08 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bus generated by hbm2java
 */
@Entity
@Table(name="bus"
    ,catalog="vutbus"
)
public class Bus  implements java.io.Serializable {


     private String regno;
     private String model;
     private int capacity;
     private Set<Assignment> assignments = new HashSet<Assignment>(0);
     private Set<Student> students = new HashSet<Student>(0);

    public Bus() {
    }

	
    public Bus(String regno, int capacity) {
        this.regno = regno;
        this.capacity = capacity;
    }
    public Bus(String regno, String model, int capacity, Set<Assignment> assignments, Set<Student> students) {
       this.regno = regno;
       this.model = model;
       this.capacity = capacity;
       this.assignments = assignments;
       this.students = students;
    }
   
     @Id 

    
    @Column(name="REGNO", unique=true, nullable=false, length=12)
    public String getRegno() {
        return this.regno;
    }
    
    public void setRegno(String regno) {
        this.regno = regno;
    }

    
    @Column(name="MODEL", length=15)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="CAPACITY", nullable=false)
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bus")
    public Set<Assignment> getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set<Assignment> assignments) {
        this.assignments = assignments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bus")
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }




}


