package Model;
// Generated 24 Feb 2016 10:33:08 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="vutbus"
)
public class Employee  implements java.io.Serializable {


     private String emplNo;
     private String empFirstname;
     private String empLastname;
     private String gender;
     private String telephoneNo;
     private String street;
     private String city;
     private String province;
     private Integer postalCode;
     private Date dateHired;
     private String type;
     private Set<Payment> payments = new HashSet<Payment>(0);
     private Set<Student> students = new HashSet<Student>(0);

    public Employee() {
    }

	
    public Employee(String emplNo) {
        this.emplNo = emplNo;
    }
    public Employee(String emplNo, String empFirstname, String empLastname, String gender, String telephoneNo, String street, String city, String province, Integer postalCode, Date dateHired, String type, Set<Payment> payments, Set<Student> students) {
       this.emplNo = emplNo;
       this.empFirstname = empFirstname;
       this.empLastname = empLastname;
       this.gender = gender;
       this.telephoneNo = telephoneNo;
       this.street = street;
       this.city = city;
       this.province = province;
       this.postalCode = postalCode;
       this.dateHired = dateHired;
       this.type = type;
       this.payments = payments;
       this.students = students;
    }
   
     @Id 

    
    @Column(name="EMPL_NO", unique=true, nullable=false, length=15)
    public String getEmplNo() {
        return this.emplNo;
    }
    
    public void setEmplNo(String emplNo) {
        this.emplNo = emplNo;
    }

    
    @Column(name="EMP_FIRSTNAME", length=30)
    public String getEmpFirstname() {
        return this.empFirstname;
    }
    
    public void setEmpFirstname(String empFirstname) {
        this.empFirstname = empFirstname;
    }

    
    @Column(name="EMP_LASTNAME", length=30)
    public String getEmpLastname() {
        return this.empLastname;
    }
    
    public void setEmpLastname(String empLastname) {
        this.empLastname = empLastname;
    }

    
    @Column(name="GENDER", length=2)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="TELEPHONE_NO", length=10)
    public String getTelephoneNo() {
        return this.telephoneNo;
    }
    
    public void setTelephoneNo(String telephoneNo) {
        this.telephoneNo = telephoneNo;
    }

    
    @Column(name="STREET", length=50)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="CITY", length=30)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="PROVINCE", length=25)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }

    
    @Column(name="POSTAL_CODE")
    public Integer getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(Integer postalCode) {
        this.postalCode = postalCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_HIRED", length=10)
    public Date getDateHired() {
        return this.dateHired;
    }
    
    public void setDateHired(Date dateHired) {
        this.dateHired = dateHired;
    }

    
    @Column(name="TYPE", length=30)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }




}


