package Model;
// Generated 24 Feb 2016 10:33:08 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="location"
    ,catalog="vutbus"
)
public class Location  implements java.io.Serializable {


     private String locationid;
     private Integer locationTicketPrice;
     private String locationname;
     private String locationStreet;
     private String locationCity;
     private String priceType;
     private Set<Schedule> schedules = new HashSet<Schedule>(0);
     private Set<Assignment> assignments = new HashSet<Assignment>(0);

    public Location() {
    }

	
    public Location(String locationid) {
        this.locationid = locationid;
    }
    public Location(String locationid, Integer locationTicketPrice, String locationname, String locationStreet, String locationCity, String priceType, Set<Schedule> schedules, Set<Assignment> assignments) {
       this.locationid = locationid;
       this.locationTicketPrice = locationTicketPrice;
       this.locationname = locationname;
       this.locationStreet = locationStreet;
       this.locationCity = locationCity;
       this.priceType = priceType;
       this.schedules = schedules;
       this.assignments = assignments;
    }
   
     @Id 

    
    @Column(name="LOCATIONID", unique=true, nullable=false, length=25)
    public String getLocationid() {
        return this.locationid;
    }
    
    public void setLocationid(String locationid) {
        this.locationid = locationid;
    }

    
    @Column(name="LOCATION_TICKET_PRICE")
    public Integer getLocationTicketPrice() {
        return this.locationTicketPrice;
    }
    
    public void setLocationTicketPrice(Integer locationTicketPrice) {
        this.locationTicketPrice = locationTicketPrice;
    }

    
    @Column(name="LOCATIONNAME", length=20)
    public String getLocationname() {
        return this.locationname;
    }
    
    public void setLocationname(String locationname) {
        this.locationname = locationname;
    }

    
    @Column(name="LOCATION_STREET", length=50)
    public String getLocationStreet() {
        return this.locationStreet;
    }
    
    public void setLocationStreet(String locationStreet) {
        this.locationStreet = locationStreet;
    }

    
    @Column(name="LOCATION_CITY", length=30)
    public String getLocationCity() {
        return this.locationCity;
    }
    
    public void setLocationCity(String locationCity) {
        this.locationCity = locationCity;
    }

    
    @Column(name="PRICE_TYPE", length=10)
    public String getPriceType() {
        return this.priceType;
    }
    
    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="location")
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="location")
    public Set<Assignment> getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set<Assignment> assignments) {
        this.assignments = assignments;
    }




}


