package Model;
// Generated 24 Feb 2016 10:33:08 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name="schedule"
    ,catalog="vutbus"
)
public class Schedule  implements java.io.Serializable {


     private String scheduleno;
     private Location location;
     private String startPoint;
     private String endPoint;
     private Date scheduleDate;
     private String scheduleTime;

    public Schedule() {
    }

	
    public Schedule(String scheduleno, Location location) {
        this.scheduleno = scheduleno;
        this.location = location;
    }
    public Schedule(String scheduleno, Location location, String startPoint, String endPoint, Date scheduleDate, String scheduleTime) {
       this.scheduleno = scheduleno;
       this.location = location;
       this.startPoint = startPoint;
       this.endPoint = endPoint;
       this.scheduleDate = scheduleDate;
       this.scheduleTime = scheduleTime;
    }
   
     @Id 

    
    @Column(name="SCHEDULENO", unique=true, nullable=false, length=10)
    public String getScheduleno() {
        return this.scheduleno;
    }
    
    public void setScheduleno(String scheduleno) {
        this.scheduleno = scheduleno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOCATIONID", nullable=false)
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    
    @Column(name="START_POINT", length=25)
    public String getStartPoint() {
        return this.startPoint;
    }
    
    public void setStartPoint(String startPoint) {
        this.startPoint = startPoint;
    }

    
    @Column(name="END_POINT", length=25)
    public String getEndPoint() {
        return this.endPoint;
    }
    
    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SCHEDULE_DATE", length=10)
    public Date getScheduleDate() {
        return this.scheduleDate;
    }
    
    public void setScheduleDate(Date scheduleDate) {
        this.scheduleDate = scheduleDate;
    }

    
    @Column(name="SCHEDULE_TIME", length=12)
    public String getScheduleTime() {
        return this.scheduleTime;
    }
    
    public void setScheduleTime(String scheduleTime) {
        this.scheduleTime = scheduleTime;
    }




}


